CREATE TABLE if not exists `ods_amazon_order_original` (
     aoo_id                          int            comment '序列ID'                               
    ,amazon_order_id                 string         comment '亚马逊定义的订单编码，格式3-7-7'                             
    ,seller_order_id                 string         comment '卖家所定义的订单编码'                             
    ,site                            string         comment '站点信息'                  
    ,company_code                    string         comment '公司代码'                          
    ,user_account                    string         comment 'amazon账户'                          
    ,purchase_date_site              string         comment '订单创建时间 site 站点时间'                                
    ,purchase_date_local             string         comment '订单创建时间 北京时间'                                 
    ,purchase_date                   string         comment '订单创建时间 UTC时间'                           
    ,last_update_date                string         comment '订单最后更新日期'                              
    ,order_status                    string         comment '当前的订单状态'                          
    ,fulfillment_channel             string         comment '订单的配送方式：亚马逊配送 (AFN) 或卖家自行配送 (MFN)。'                                 
    ,sales_channel                   string         comment '销售渠道'                           
    ,order_channel                   string         comment '订单渠道'                           
    ,ship_service_level              string         comment '订单的发货服务水平.针对中国地区卖家自行配送（MFN）有效值为：Std CN D2D：快递，Std CN Postal：平邮，Exp CN EMS：EMS'                                
    ,order_type                      string         comment '订单类型(StandardOrder - 包含当前有库存商品的订单。)'                        
    ,currency_code                   string         comment '币种'                           
    ,amount                          decimal(10,4)  comment '接口返回原始金额'                           
    ,sale_amount                     decimal(10,4)  comment '销售额，自己计算的'                                
    ,payment_method                  string         comment '订单的付款方式。有效值为： COD、CVS 和 Other。'                            
    ,marketplace_id                  string         comment '商城编码'                            
    ,buyer_email                     string         comment '买家邮箱'                         
    ,buyer_name                      string         comment '买家姓名'                        
    ,earliest_ship_date              string         comment '订单配送的最早日期，仅当 OrderType = Preorder 时才返回'                                
    ,latest_ship_date                string         comment '订单配送的最晚日期，仅当 OrderType = Preorder 时才返回'                              
    ,shipment_service_level_category string         comment '运费服务等级分类'                                             
    ,shipped_amazon_tfm              string         comment '指明订单配送方是否是亚马逊配送服务 (Amazon TFM，仅适用于中国地区。)。'                                
    ,tfm_shipment_status             string         comment '亚马逊 TFM 订单的状态，PendingPickUp'                                 
    ,cba_displayable_shipping_label  string         comment '卖家自定义的配送方式，属于 Checkout By Amazon (CBA) 所支持的四种标准配送设置中的一种.(仅适用于美国 (US)、英国 (UK) 和德国 (DE) 的卖家)'                                            
    ,number_items_shipped            int            comment '已配送商品数量'                               
    ,number_items_unshipped          int            comment '未配送商品数量'                                 
    ,shipping_address_name           string         comment '配送地址-姓名'                                   
    ,shipping_address_phone          string         comment '配送地址-电话'                                    
    ,shipping_address_country_code   string         comment '配送地址-国家二字码'                                           
    ,shipping_address_state          string         comment '配送地址-州/省'                                    
    ,shipping_address_district       string         comment '配送地址-区'                                       
    ,shipping_address_county         string         comment '配送地址-县'                                     
    ,shipping_address_city           string         comment '配送地址-城市'                                   
    ,shipping_address_postal_code    string         comment '配送地址-邮政编码'                                          
    ,shipping_address_address1       string         comment '配送地址-地址1'                                       
    ,shipping_address_address2       string         comment '配送地址-地址2'                                       
    ,shipping_address_address3       string         comment '配送地址-地址3'                                       
    ,shipping_address_type           string         comment '配置地址类型'                                   
    ,is_loaded                       int            comment '订单信息是否下载完毕。0:下载订单未下载items，1:订单、items信息都已下载，2:已生成订单，3:存在相同的单号'                    
    ,purchase_order_number           string         comment '采购单号'                                   
    ,is_business_order               string         comment '是否为B2B订单'                               
    ,is_prime                        string         comment ''                      
    ,earliest_delivery_date          string         comment '订单预计妥投最早时间 ，仅当 OrderType = Preorder 时才返回'                                    
    ,latest_delivery_date            string         comment '订单预计妥投最晚时间，仅当 OrderType = Preorder 时才返回'                                  
    ,is_sold_by_ab                   string         comment 'IsSoldByAB'                           
    ,created_time                    string         comment '创建时间'                          
    ,updated_time                    string         comment '系统最后更新时间'                          
    ,ods_create_time                 string         comment '导入数据时间'
) comment 'amazon原始订单表'
row format delimited fields terminated by '\t' stored as textfile;





