CREATE TABLE if not exists ods_company (
     company_id             int     comment  ''            
    ,company_code          string  comment  '客户代码'                  
    ,company_short         string  comment  '简称'                   
    ,company_name          string  comment  '客户名称'                  
    ,company_auth          string  comment  '授权编码'                  
    ,company_type          int     comment  '公司类型'               
    ,company_status        int     comment  '客户状态 0=已注销 1=待激活 2=已停用 3=已激活'                 
    ,company_level         int     comment  '客户等级 0=未绑定  关联sys_base_levell等级表'                
    ,verified_status       int     comment  '认证状态：0未认证,1待审核.2未通过，3审核中，4认证失败，5认证通过'                  
    ,mobile                string  comment  '联系方式'           
    ,company_name_cn       string  comment  '公司名称-中文'                     
    ,company_inner_source  int     comment  '注册来源 1 ERP. 2 用户中心'                       
    ,company_source        int     comment  '注册来源 1 ERP. 2 用户中心'                 
    ,deploy_status         int     comment  '部署状态 1初始化 2部署中3部署失败 4已部署'                
    ,season                string  comment  '失败原因'            
    ,db_code               string  comment  '数据库编码'           
    ,currency_local        string  comment  '本位币设置，默认为RMB。'                   
    ,created_time          string  comment  '建立时间'                  
    ,updated_time          string  comment  '更新时间'                  
    ,ods_create_time       string  comment  '导入数据时间'                     
) COMMENT '客户主表'
row format delimited fields terminated by '\t' stored as textfile;                                             