CREATE TABLE if not exists dwm_child_listing_sum_d (
    `user_account` string  COMMENT '店铺账号',
    `site` string  COMMENT '站点',
    `seller_sku` string comment '',
    `asin` string comment '',
    `qty` int  COMMENT '销售数量',
    `summary_date` string  COMMENT '统计日期',
    `sale_amount` decimal(14,4)  COMMENT '销售额(本位币)',
    `sale_amount_usd` decimal(14,4)  COMMENT '销售额美元',
    `sale_amount_eur` decimal(14,4)  COMMENT '销售额欧元',
    `sale_amount_gbp` decimal(14,4)  COMMENT '销售额英镑',
    `sale_amount_jpy` decimal(14,4)  COMMENT '销售额日元',
    `sale_amount_original` decimal(14,4)  COMMENT '销售额（站点原始金额）',
    `created_time` string   COMMENT '创建时间',
    `updated_time` string   COMMENT '更新时间',
    `sale_order_num` int  COMMENT '订单数',
    `refund_amount` int  COMMENT '退款listing个数',
    `refund_money` decimal(14,4)  COMMENT '退款金额(站点币种)',
    `refund_money_usd` decimal(14,4)  COMMENT '退款金额美元',
    `refund_money_eur` decimal(14,4)  COMMENT '退款金额欧元',
    `refund_money_gbp` decimal(14,4)  COMMENT '退款金额英镑',
    `refund_money_jpy` decimal(14,4)  COMMENT '退款金额日元',
    `refund_money_local` decimal(14,4)  COMMENT '退款金额(本位币)',
    `key1` string COMMENT 'user_account+asin+seller_sku 的MD5值',
    `return_amount` int  COMMENT '退货数',
    `asin_type` int  COMMENT '子asin:1，独立产品:2',
    `ad_qty` int  COMMENT '广告销售数量',
    `ad_sale_amount` decimal(14,4)  COMMENT '广告销售额(本位币)',
    `ad_sale_amount_usd` decimal(14,4)  COMMENT '广告销售额美元',
    `ad_sale_amount_eur` decimal(14,4)  COMMENT '广告销售额欧元',
    `ad_sale_amount_gbp` decimal(14,4)  COMMENT '广告销售额英镑',
    `ad_sale_amount_jpy` decimal(14,4)  COMMENT '广告销售额日元',
    `ad_sale_order_num` int  COMMENT '广告订单数',
    `ad_sale_amount_original` decimal(14,4)  COMMENT '广告销售额（站点原始金额）',
    `cost` decimal(14,4)  COMMENT '广告花费(站点币种)',
    `cost_local` decimal(14,4)  COMMENT '广告花费(本位币)',
    `cost_usd` decimal(14,4) comment '',
    `cost_eur` decimal(14,4) comment '',
    `cost_gbp` decimal(14,4) comment '',
    `cost_jpy` decimal(14,4) comment '',
    `clicks` int  COMMENT '广告访问次数,也即广告点击数',
    `impressions` int  COMMENT '广告曝光量',
    `sessions` int  COMMENT '访客次数',
    `page_views` int  COMMENT '浏览次数',
    `buy_box_percentage` decimal(10,2)  COMMENT 'buy_box_percentage',
    `session_percentage` decimal(10,2)  COMMENT '买家访问次数比率',
    `page_views_percentage` decimal(10,2)  COMMENT '浏览次数比率'
) comment '子asin和独立asi统计表(本地时间)'
partitioned by (company_code string comment '公司代码',day string comment '统计日期')
row format delimited fields terminated by '\t' stored as orc;