CREATE TABLE if not exists ods_platform_user (
     pu_id                    int  comment ''
    ,user_account             string COMMENT '平台账号'
    ,short_name               string COMMENT '简称'
    ,site                     string COMMENT '站点'
    ,seller_id                string COMMENT 'Amazon-销售ID/卖家ID'
    ,currency_code            string COMMENT '站点币种'
    ,status                   int    COMMENT '状态，0禁用，1：启用 2:临时禁用'
    ,date_create              string COMMENT '添加时间'
    ,platform_user_name       string COMMENT '平台登录名称'
    ,final_value_fee_currency string comment ''
    ,erp_user_id              string COMMENT '系统用户id'
    ,auth_type                int  COMMENT '是否平台项目授权 1是 0否'
    ,account_tax_id           string COMMENT '店铺税号'
    ,is_create_product        int  COMMENT 'FBA极速版是否自动创建产品'
    ,is_create_warehouse      int  COMMENT 'FBA极速版是否自动创建仓库/运输方式等信息'
    ,is_account_mark          int  COMMENT '是否开启账号标发，1是0否'
    ,shopowner                int  COMMENT '店长'
    ,auth_status              int   COMMENT '授权状态：0未授权，1已授权，2授权异常，3异常，4授权过期'
    ,ad_auth_status           int   COMMENT '广告授权状态：0未授权，1已授权'
    ,product_ad_auth_status   int   COMMENT '是否商品广告授权'
    ,brand_ad_auth_status     int  COMMENT '是否品牌广告授权'
    ,display_ad_auth_status   int  COMMENT '是否展示型广告授权'
    ,is_del                   int   COMMENT '是否删除：0正常账号，1删除的账号'
    ,marketplace_id          string    COMMENT '市场编号'
    ,access_key             string   COMMENT '访问秘钥-ID'
    ,secret_key             string   COMMENT '访问秘钥-Token'
    ,developer_number        string    COMMENT '开发编号'
    ,mws_auth_token          string    COMMENT 'mws授权token'
    ,merchant_id             string    COMMENT '卖家ID'
    ,oauth_token             string   COMMENT 'OAuth token'
    ,refresh_token          string   COMMENT 'Refresh token'
    ,expires_in             string   COMMENT 'token过期时间'
    ,oauth_expires_in       string   COMMENT 'oauth的过期时间'
    ,oauth_client_id        string   COMMENT 'oauth client id'
    ,oauth_client_secret    string   COMMENT 'oauth client secret'
    ,platform               string comment 'amazon'
    ,created_time           string COMMENT '创建时间'
    ,updated_time           string comment '更新时间'
    ,pu_type                int     comment ''  
    ,ods_create_time   string comment '导入数据时间'
) comment '用户表'
partitioned by (company_code string comment '公司代码')
row format delimited fields terminated by '\t' stored as textfile;