CREATE TABLE if not exists `ods_amazon_business_report_by_parent` (
     id                          int           comment ''         
    ,user_account                string        comment '店铺账号'           
    ,seller_id                   string        comment '卖家销售id'        
    ,site                        string        comment '站点'   
    ,parent_asin                 string        comment '父asin'          
    ,title                       string        comment '标题'    
    ,sessions                    int           comment '买家访问次数'    
    ,session_percentage          decimal(10,2) comment '买家访问次数百分比'                        
    ,page_views                  int           comment '页面浏览次数'      
    ,page_views_percentage       decimal(10,2) comment '页面浏览次数百分比'                           
    ,buy_box_percentage          decimal(10,2) comment '购买按钮赢得率'                        
    ,units_ordered               int           comment '已订购商品数量'         
    ,units_ordered_b2b           int           comment '订购数量 – B2B'             
    ,unit_session_percentage     decimal(10,2) comment '订单商品数量转化率'                             
    ,unit_session_percentage_b2b decimal(10,2) comment '订单商品数量转化率b2b'                                 
    ,currency                    string        comment '币种'       
    ,ordered_product_sales       decimal(10,2) comment '已订购商品销售额'                           
    ,ordered_product_sales_b2b   decimal(10,2) comment '已订购商品的销售额 – B2B'                               
    ,total_order_items           int           comment '订单商品种类数'             
    ,total_order_items_b2b       int           comment '订单商品总数 – B2B'                 
    ,generate_date               string          comment '爬取日期'          
    ,created_time                string        comment ''           
    ,updated_time                string        comment ''           
    ,ods_create_time           string           comment '导入数据时间'
) comment 'BusinessReport流量报告父asin维度'
partitioned by (company_code string comment '公司代码')
row format delimited fields terminated by '\t' stored as textfile;
