CREATE TABLE if not exists `ymx.ods_product_ad_products_report_daily` (
     paprdy_id                 int             comment ''                     
    ,user_account              string          comment '平台账号'                
    ,profile_id                bigint          comment 'profileId'              
    ,campaign_id               bigint          comment '活动campaignId'               
    ,campaign_name             string          comment '活动名称'                 
    ,ad_group_id               bigint          comment '广告组ID'               
    ,ad_group_name             string          comment '广告组名称'                 
    ,asin                      string          comment 'ASIN'        
    ,sku                       string          comment 'SKU'       
    ,item_name                 string          comment '产品名称'             
    ,aapr_status               string          comment '产品状态 enabled:启用,paused:暂停,archived:归档、删除'               
    ,ad_id                     bigint          comment '广告产品ID'         
    ,currency                  string          comment '币种'            
    ,impressions               int             comment '曝光度'            
    ,clicks                    int             comment '点击数'       
    ,cost                      decimal(10,4)   comment '所有点击的总费用'               
    ,generated_date            string          comment '报告生成生成日期'                
    ,conversions1d             int             comment '点击广告1天内发生的归因转化事件数'              
    ,conversions1d_same_sku    int             comment '点击广告后1天内发生的归因转化事件的数量，其中已购买的SKU与广告中的SKU相同'                       
    ,units_ordered1d           int             comment '点击广告后1天内订购的归属订单数量'                
    ,units_ordered1d_same_sku  int             comment '点击的广告在1天内订购的归因单位数（购买的SKU与广告的SKU相同）'                         
    ,sales1d                   decimal(10,4)   comment '点击广告后1天内发生的归因销售数量'                  
    ,sales1d_same_sku          decimal(10,4)   comment '在购买的SKU与广告中的SKU相同的广告点击后的1天内发生的归因销售总值'                           
    ,conversion1d_rate         decimal(10,4)   comment '1天内转化率：1天订单数/点击次数'                            
    ,ctr                       decimal(10,4)   comment '点击率：点击数/曝光数'              
    ,cpc                       decimal(10,4)   comment 'CPC ：广告费/点击数'              
    ,acos1d                    decimal(10,4)   comment '1天内ACoS：广告费/1天销售额'                 
    ,product_amount            decimal(10,4)   comment '该sku的销售额'                         
    ,create_id                 int             comment '创建人'          
    ,created_time              string          comment '添加时间'                
    ,update_id                 int             comment '修改人'          
    ,updated_time              string          comment '更新时间'                
    ,order_proportion          decimal(10,4)   comment '广告订单占比：广告总订单量/店铺总订单量'                           
    ,sale_proportion           decimal(10,4)   comment '广告销售额占比：广告总销售额/店铺销售额'                          
    ,cost_proportion           decimal(10,4)   comment '广告花费占比：广告总花费/店铺销售额'                          
    ,cpa                       decimal(10,4)   comment '单位订单平均广告花费：广告总花费/广告总订单量'              
    ,roas                      decimal(10,4)   comment '广告产出投入比：广告总销售额/广告总花费'               
    ,conversions7d             int             comment '点击广告7天内发生的归因转化事件数'              
    ,conversions7d_same_sku    int             comment '点击广告后7天内发生的归因转化事件的数量，其中已购买的SKU与广告中的SKU相同'                       
    ,units_ordered7d           int             comment '点击广告后1天内订购的归属订单数量'                
    ,sales7d                   decimal(10,4)   comment '点击广告后7天内发生的归因销售数量'                  
    ,sales7d_same_sku          decimal(10,4)   comment '在购买的SKU与广告中的SKU相同的广告点击后的7天内发生的归因销售总值'                           
    ,conversion7d_rate         decimal(10,4)   comment '7天内转化率：7天订单数/点击次数'                            
    ,acos7d                    decimal(10,4)   comment '7天内ACoS： 广告费/7天销售额'                 
    ,units_ordered7d_same_sku  int             comment '点击广告后7天内订购的归因单位数（购买的SKU与广告的SKU相同）'                         
    ,order_amount              decimal(10,4)   comment '时间段内店铺金额'                       
    ,order_total               int             comment '时间段内订单数量'            
    ,ods_create_time           string           comment '导入数据时间'
) comment 'Amazon广告产品报告日表'
partitioned by (company_code string comment '公司代码')
row format delimited fields terminated by '\t' stored as textfile;

create table if not exists ymx_tmp.ods_product_ad_products_report_daily like ymx.ods_product_ad_products_report_daily;