CREATE TABLE if not exists `ods_amazon_order_detail` (
     aod_id                            int       comment '自增长序列'                          
    ,aoo_id                            int       comment 'amazon订单原始表主键ID'                                
    ,user_account                      string   comment '店铺账号'                                    
    ,amazon_order_id                   string   comment '亚马逊所定义的订单编码，格式3-7-7'                                       
    ,asin                              string   comment '商品的亚马逊商品编码'                            
    ,seller_sku                        string   comment '销售SKU'                                  
    ,order_item_id                     string   comment '亚马逊所定义的订单商品编码'                                     
    ,title                             string   comment '商品的名称'                             
    ,quantity_ordered                  int       comment '订单中的商品数量。'                                    
    ,quantity_shipped                  int       comment '已配送的商品数量'                                    
    ,gift_message_text                 string   comment '由买方提供的礼物消息'                                         
    ,item_sale_amount                  decimal(10,4)   comment 'item的销售额，自己计算的'                                        
    ,gift_wrap_level                   string   comment '买家指定的礼品包装等级'                                       
    ,item_price_currency_code          string   comment '商品的售价，币种'                                                
    ,item_price_amount                 decimal(10,4)   comment '商品的售价-金额，请注意，订单商品涉及到商品及其数量。即，ItemPrice 的值等于 商品的售价 x 商品的订购数量。另外，ItemPrice 不包括 ShippingPrice 和 GiftWrapPrice。'                                         
    ,shipping_price_currency_code      string   comment '商品配送费用-币种'                                                    
    ,shipping_price_amount             decimal(10,4)   comment '商品配送费用-金额'                                             
    ,gift_wrap_price_currency_code     string   comment '礼品包装费用-币种'                                                     
    ,gift_wrap_price_amount            decimal(10,4)   comment '礼品包装费用-金额'                                              
    ,item_tax_currency_code            string   comment '商品价格所缴税费-币种'                                              
    ,item_tax_amount                   decimal(10,4)   comment '商品价格所缴税费'                                       
    ,shipping_tax_currency_code        string   comment '商品配送费用所缴税费-币种'                                                  
    ,shipping_tax_amount               decimal(10,4)   comment '商品配送费用所缴税费-金额'                                           
    ,gift_wrap_tax_currency_code       string   comment '礼品包装费用所缴税费-币种'                                                   
    ,gift_wrap_tax_amount              decimal(10,4)   comment '礼品包装费用所缴税费-金额'                                            
    ,shipping_discount_currency_code   string   comment '商品配送费用所享折扣-币种'                                                       
    ,shipping_discount_amount          decimal(10,4)   comment '商品配送费用所享折扣-金额'                                                
    ,promotion_discount_currency_code  string   comment '报价中的总促销折扣-币种'                                                        
    ,promotion_discount_amount         decimal(10,4)   comment '报价中的总促销折扣-金额'                                                 
    ,cod_fee_currency_code             string   comment '货到付款服务收取的费用-币种'                                             
    ,cod_fee_amount                    decimal(10,4)   comment '货到付款服务收取的费用-金额'                                      
    ,cod_fee_discount_currency_code    string   comment '货到付款费用的折扣-币种'                                                      
    ,cod_fee_discount_amount           decimal(10,4)   comment '货到付款费用的折扣-金额'                                               
    ,invoice_requirement               string   comment '发票要求信息(Individual - 买家要求对订单中的每件商品单独开具发票。)'                                           
    ,invoice_buyer_selected_category   string   comment '买家在下订单时选择的发票类目信息'                                                       
    ,invoice_title                     string   comment '买家指定的发票抬头'                                     
    ,invoice_information               string   comment '发票要求信息(NotApplicable - 买家不要求开具发票。)'                                           
    ,condition_id                      string   comment '商品的状况(New,Used...)'                                    
    ,condition_subtype_id              string   comment '商品的子状况(New,Mint.....)'                                            
    ,condition_note                    string   comment '卖家描述的商品状况'                                      
    ,scheduled_delivery_start_date     string  comment '订单预约送货上门的开始日期（目的地时区）'                                                      
    ,scheduled_delivery_end_date       string  comment '订单预约送货上门的终止日期（目的地时区）'                                                    
    ,price_designation                 string   comment '商业价格'                                         
    ,payments_date                     string   comment '付款日期'                                     
    ,buyer_phone_number                string   comment '买家手机号'                                          
    ,delivery_instructions             string   comment '配送说明'                                             
    ,delivery_time_zone                string   comment '交货时区'                                          
    ,created_time                      string  comment '创建时间'                                     
    ,updated_time                      string  comment '更新时间'                                     
    ,ods_create_time                   string    comment '导入数据时间'
) comment 'amazon原始订单明细表'
partitioned by (company_code string comment '公司代码')
row format delimited fields terminated by '\t' stored as textfile;